//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuuTru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LuuTru()
        {
            this.HoaDon = new HashSet<HoaDon>();
            this.SuDungDichVu = new HashSet<SuDungDichVu>();
        }
    
        public int LuuTruId { get; set; }
        public int PhongId { get; set; }
        public int KhachHangId { get; set; }
        public System.DateTime CheckInDuKien { get; set; }
        public System.DateTime CheckOutDuKien { get; set; }
        public Nullable<System.DateTime> CheckInThucTe { get; set; }
        public Nullable<System.DateTime> CheckOutThucTe { get; set; }
        public int SoNguoiLon { get; set; }
        public int SoTreEm { get; set; }
        public string TrangThai { get; set; }
        public decimal TienCoc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TaoBoiNguoiDungId { get; set; }
        public System.DateTime TaoLuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuDungDichVu> SuDungDichVu { get; set; }
    }
}
