//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatChiTiet
    {
        public int PhieuXuatChiTietId { get; set; }
        public int PhieuXuatId { get; set; }
        public int VatTuId { get; set; }
        public decimal SoLuong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuXuat PhieuXuat { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
