//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapChiTiet
    {
        public int PhieuNhapChiTietId { get; set; }
        public int PhieuNhapId { get; set; }
        public int VatTuId { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
