//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuat()
        {
            this.PhieuXuatChiTiet = new HashSet<PhieuXuatChiTiet>();
        }
    
        public int PhieuXuatId { get; set; }
        public System.DateTime NgayXuat { get; set; }
        public string LyDo { get; set; }
        public Nullable<int> NguoiDungId { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatChiTiet> PhieuXuatChiTiet { get; set; }
    }
}
