//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        public int SuDungDichVuId { get; set; }
        public int LuuTruId { get; set; }
        public int DichVuId { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public System.DateTime TaoLuc { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> HoaDonId { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual LuuTru LuuTru { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
